### ISSUE TITLE
Trying to select text let's the page jump to the top again

### ISSUE THREAD

**Issue by almereyda** [maxlath/inventaire#1]
I'm often marking text with the mouse cursor, so it's easier for my eyes to follow where I'm reading.
Unfortunately, https://inventaire.io/welcome currently jumps back to the top when trying this.

**Comment by maxlath** [comment]
thank you Jon for this first issue :D
there is a different repo for the client side, so there is [the bug-fix](https://github.com/maxlath/inventaire-client/commit/0cc4f5374778ee1397d003c99be2dc576e6a974f)

**Comment by almereyda** [comment]
Cool. I'm closing down here then.

Btw., for server-side collection management, you may also want to have a look at http://falkland-cms.com/ ...

**Comment by maxlath** [comment]
@almereyda thanks! it's will have a look at that
