### ISSUE TITLE
Main welcome content, scrolling issue

### ISSUE THREAD

**Issue by Jitrixis** [maxlath/inventaire#17]
Hi,

Recently, I create my account and at the welcome screen the main content is larger than the view so you get a scroll useless and looking bad if you scroll and causing some problem.

Cordialy.

![capture du 2015-05-26 01 55 57](https://cloud.githubusercontent.com/assets/3462094/7803271/615c0d28-034b-11e5-8ec2-79446f71f29d.png)

**Comment by maxlath** [comment]
this should have been fixed by [this commit](https://github.com/maxlath/inventaire-client/commit/c1f9a411ab35105ddf6d70b00ebf16fe95ed2009) and now be online, can you have a look to confirm?
