### ISSUE TITLE
French search doesn't return book overview from Wikidata

### ISSUE THREAD

**Issue by frimelle** [maxlath/inventaire#19]
When I set my language in the settings to French, I don't see the overview of the books with the image and the link to Wikidata etc. It works for when I set the language to German though.
I reproduced the bug on other peoples accounts.

**Comment by maxlath** [comment]
I'm not sure to see which books overview your are talking about, could you take a screenshot?

**Comment by frimelle** [comment]
So, I can't reproduce the bug, which is cool, I guess. I was talking about this overview;

![victor-hugo-de](https://cloud.githubusercontent.com/assets/2714560/7859801/29c37392-0544-11e5-9951-9c31605c8093.png)

You would just not see this part but directly the list of books underneath.

**Comment by frimelle** [comment]
Looks good now. We could close this one and open it again if I can somehow reproduce it?

**Comment by maxlath** [comment]
ok
