### ISSUE TITLE
layout book presentations

### ISSUE THREAD

**Issue by unteem** [maxlath/inventaire#26]
The text on book presentations goes over the image

![Uploading screenshot-inventaire.jpg…]()

**Comment by unteem** [comment]
This problem seems to be specific to chromium
I did not test on other browsers than firefox though

**Comment by maxlath** [comment]
thanks for reporting!
fixed by commit https://github.com/maxlath/inventaire-client/commit/2ede6d2051160ce7c45f632457a391c46d4522ee
