### ISSUE TITLE
Some books cannot be added to my library

### ISSUE THREAD

**Issue by studiodev** [maxlath/inventaire#6]
Hello,

When I try to add some books, from the search or with the isbn, the entry is not persisted correctly.
When I validate the addition, I see the book in my library, but after a refresh, the book is gone.

Book in error :
* https://inventaire.io/entity/isbn:9780133488746/Project_Retrospectives/add
* https://inventaire.io/entity/isbn:9780131479418/Agile_Estimating_and_Planning/add

The request to add the book fail with a 400 error :

    curl "https://inventaire.io/api/6a65aa87e68e161650bf7741ad010156/items/6a65aa87e68e161650bf7741ad010156:isbn:9780133488746:1423503620965" -X PUT -H "cookie: express:sess=################=; express:sess.sig=########; email=yotsumi.########"%"40gmail.com; lang=fr" -H "x-requested-with: XMLHttpRequest"  -H "content-type: application/json" -H "accept: application/json, text/javascript, */*; q=0.01" -H "referer: https://inventaire.io/entity/isbn:9780133488746/Project_Retrospectives/add" --data-binary "{""title"":""Project Retrospectives"",""entity"":""isbn:9780133488746"",""claims"":{""P31"":""isbn:9780133488746""},""transaction"":""inventorying"",""pictures"":[""http://books.google.com/books/content?id=3VUUAAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api"",""http://books.google.com/books/content?id=3VUUAAAAQBAJ&printsec=frontcover&img=1&zoom=2&source=gbs_api""],""owner"":""6a65aa87e68e161650bf7741ad010156"",""created"":1423503620965,""_id"":""6a65aa87e68e161650bf7741ad010156:isbn:9780133488746:1423503620965"",""listing"":""friends"",""comment"":"""",""notes"":""""}" --compressed```

Response: 400 with "invalid item: AssertionError: false == true"

**Comment by maxlath** [comment]
thanks for opening this issue! 
I saw error logs for "hand-made" entites - ones with ids like inv:d6b6138a-7515-425b-b3fc-542619a1305b, which were caused by this bad regexp, but not for isbn entities, I might have closed the issue a bit early, can you re-try to add it again?

**Comment by studiodev** [comment]
I've retried with the Agile estimating and planning" book, the problem is still present.
The same with another mainstream book: "isbn:9782226279798".

![Simulation](http://g.recordit.co/PwWnNPJLRE.gif)

**Comment by maxlath** [comment]
should have been fixed by 1565819
can you retry?

**Comment by studiodev** [comment]
Perfect! Thanks
