### ISSUE TITLE
Allow to search books by isbn without prefixing 'isbn:' and strip dashes

### ISSUE THREAD

**Issue by studiodev** [maxlath/inventaire#7]
Currently the search doesn't work as explained in the quick tour.

It's compulsory to prefix the code by 'isbn:'  to make the isbn seach working. I should be optional.

Now: https://inventaire.io/search?isbn:9782226244222 
Expected: https://inventaire.io/search?9782226244222

In addition, dashes should be striped from the code because isbn are always printed with many dashes on the book.

Expected: https://inventaire.io/search?978-2-226-24422-2

**Comment by maxlath** [comment]
thanks!
should have been fixed by commit 8e59af9
I let you close the issue then

**Comment by studiodev** [comment]
Good job, it works fine :+1:
