### ISSUE TITLE
page doesn't load first time

### ISSUE THREAD

**Issue by lydiapintscher** [maxlath/inventaire#8]
When I loaded inventaire.io for the first time no content was shown. This has been reproduced by several people. It doesn't seem to matter if it is the main page or a specific other page.

**Comment by maxlath** [comment]
thanks for the report, there seem to be many browser compatibilities issues. Can you try to connect at this address with the browsers experiencing this problem? [https://92.222.76.42](https://92.222.76.42)
It's the same code but not minified, so easier to debug :)
It will ask for a security exception as it's a self-signed certificate

**Comment by lydiapintscher** [comment]
The same issue happens there, yes.

**Comment by maxlath** [comment]
got it, thanks! can you try to connect again on this same server?

for the details:
Got an obscure bug report from bluebird (promises lib), there seem to be a problem with the way first requests errors are handled.
I cancelled the reqeuest from not-logged users, that were doomed to get 401 errors and try to `catch` more agressively to get better logs at least.

```
   [ 'Uncaught Error: [object Object] https://92.222.76.42/public/javascripts/vendor.js?DIGEST 18623:19',
     [ 'Error: [object Object]',
       '    at Object.rejectFromThenable (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:20150:60)',
       '    at Object.<anonymous> (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:3322:33)',
       '    at fire (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:3165:30)',
       '    at Object.self.add [as fail] (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:3211:7)',
       '    at Array.<anonymous> (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:3321:28)',
       '    at Function.jQuery.extend.each (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:467:23)',
       '    at Object.<anonymous> (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:3318:14)',
       '    at Function.jQuery.extend.Deferred (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:3378:9)',
       '    at Object.promise.then (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:3317:20)',
       '    at doThenable (https://92.222.76.42/public/javascripts/vendor.js?DIGEST:20114:14)' ] ],
```

**Comment by lydiapintscher** [comment]
Now it seems to work :)

**Comment by maxlath** [comment]
yeah!! thanks !!
